Wed Apr  8 02:25:26 2015
Traceback (most recent call last):
  File "log_thebutton_stream.py", line 24, in <module>
    _ = f.write(ws.recv() + '\n')
  File "C:\Python33\lib\site-packages\websocket\_core.py", line 332, in recv
    opcode, data = self.recv_data()
  File "C:\Python33\lib\site-packages\websocket\_core.py", line 349, in recv_data
    opcode, frame = self.recv_data_frame(control_frame)
  File "C:\Python33\lib\site-packages\websocket\_core.py", line 362, in recv_data_frame
    frame = self.recv_frame()
  File "C:\Python33\lib\site-packages\websocket\_core.py", line 394, in recv_frame
    return self.frame_buffer.recv_frame()
  File "C:\Python33\lib\site-packages\websocket\_abnf.py", line 300, in recv_frame
    self.recv_header()
  File "C:\Python33\lib\site-packages\websocket\_abnf.py", line 249, in recv_header
    header = self.recv_strict(2)
  File "C:\Python33\lib\site-packages\websocket\_abnf.py", line 334, in recv_strict
    bytes = self.recv(min(16384, shortage))
  File "C:\Python33\lib\site-packages\websocket\_core.py", line 460, in _recv
    return recv(self.sock, bufsize)
  File "C:\Python33\lib\site-packages\websocket\_socket.py", line 77, in recv
    bytes = sock.recv(bufsize)
  File "C:\Python33\lib\ssl.py", line 438, in recv
    return self.read(buflen)
  File "C:\Python33\lib\ssl.py", line 329, in read
    v = self._sslobj.read(len or 1024)
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

Wed Apr  8 09:37:18 2015
Traceback (most recent call last):
  File "log_thebutton_stream.py", line 24, in <module>
    print('Writing to ' + FILE + '\n')
  File "C:\Python33\lib\site-packages\websocket\_core.py", line 332, in recv
    opcode, data = self.recv_data()
  File "C:\Python33\lib\site-packages\websocket\_core.py", line 349, in recv_data
    opcode, frame = self.recv_data_frame(control_frame)
  File "C:\Python33\lib\site-packages\websocket\_core.py", line 362, in recv_data_frame
    frame = self.recv_frame()
  File "C:\Python33\lib\site-packages\websocket\_core.py", line 394, in recv_frame
    return self.frame_buffer.recv_frame()
  File "C:\Python33\lib\site-packages\websocket\_abnf.py", line 300, in recv_frame
    self.recv_header()
  File "C:\Python33\lib\site-packages\websocket\_abnf.py", line 249, in recv_header
    header = self.recv_strict(2)
  File "C:\Python33\lib\site-packages\websocket\_abnf.py", line 334, in recv_strict
    bytes = self.recv(min(16384, shortage))
  File "C:\Python33\lib\site-packages\websocket\_core.py", line 460, in _recv
    return recv(self.sock, bufsize)
  File "C:\Python33\lib\site-packages\websocket\_socket.py", line 77, in recv
    bytes = sock.recv(bufsize)
  File "C:\Python33\lib\ssl.py", line 438, in recv
    return self.read(buflen)
  File "C:\Python33\lib\ssl.py", line 329, in read
    v = self._sslobj.read(len or 1024)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

